sudo: required

language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

services:
 - rabbitmq

env:
  - PYTHONASYNCIODEBUG=1

before_script:
  - sudo rabbitmqctl add_vhost "aiorabbit"

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script: bash run_tests.sh

