sudo: required

language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

services:
 - rabbitmq

env:
  - PYTHONASYNCIODEBUG=1

before_script:
  - sudo rabbitmqctl add_vhost "aiorabbit"
  - sudo RABBITMQ_NODE_PORT=5673 RABBITMQ_SERVER_START_ARGS="-rabbitmq_management listener [{port,15673}]" RABBITMQ_NODENAME=hare rabbitmq-server -detached

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo rabbitmq-plugins enable rabbitmq_federation
  - sudo rabbitmq-plugins enable rabbitmq_federation_management
  - sudo service rabbitmq-server restart

script: bash run_tests.sh

