sudo: required
addons:
  hosts:
    - rabbit
    - hare

language: python

python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

services:
 - rabbitmq

env:
  - PYTHONASYNCIODEBUG=1

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

before_script: run-tests.sh

script: nosetests --verbosity=2 aiorabbitmq

