sudo: required

language: python

python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

services:
 - docker

env:
  - PYTHONASYNCIODEBUG=1
  - DOCKER_COMPOSE_VERSION=1.6

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo pip install docker-compose
  - docker-compose start

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script: nosetests --verbosity=2 aiorabbitmq

