sudo: required

language: python

python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

env:
  - PYTHONASYNCIODEBUG=1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
  - docker-compose start

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script: nosetests --verbosity=2 aiorabbitmq

