sudo: required

language: python

services:
 - docker

python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

env:
  global:
    - PYTHONASYNCIODEBUG=1
    - DOCKER_VERSION=1.10.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  - sudo apt-get update -q
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker version
  - docker-compose version

install:
  - docker-compose up -d
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - sleep 3

script: nosetests --verbosity=2 aiorabbitmq

